src/django_src/django_src/urls.py
import sys
sys.path.append("..")
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from users import views as user_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('code_reception.urls')),
    path('', include('teacher_controls.urls')),
    path('register/', user_view.register, name='register'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_view.profile, name='profile'),

    #path('', include('code_reception.urls')),
]

src/django_src/teacher_controls/urls.py
from django.urls import path, re_path
from django.views.i18n import JavaScriptCatalog
from . import views
from code_reception.views import all_choose_course

urlpatterns = [
    path('create_course/', views.create_course, name='create_course'),
    path('create_task/', views.create_task, name='create_task'),
    path('controls/<int:course>/', views.course_controls, name='course_controls'),
    path('assign_tasks/', views.assign_tasks, name='assign_tasks'),
    re_path(r'^admin/jsi18n/$', JavaScriptCatalog().get_catalog),
    # path('get_course/controls/', views.course_controls, name='course_controls'),
    # path('get_course/', all_choose_course, name='all_courses_view'),
]

src/django_src/code_reception/models.py
import json

from django.contrib.auth.models import User
from django.db import models
from users.models import StudentGroup

from users.models import Profile
from .default_values import CPP_TEMPLATE



# Create your models here.

class Task(models.Model):
    Question_id = models.IntegerField(default=-1)
    title = models.CharField(max_length=100)
    text = models.TextField()
    timeout = models.FloatField(default=3.0)
    user_set = models.ManyToManyField(User)

    def __str__(self):
        return self.title

    @staticmethod
    def get_all_tasks():
        return [task.title for task in Task.objects.all()]

    def to_question_json(self):
        return {
            "QuestionID": self.Question_id,
            "Title": self.title,
            "Text": self.text,
            "Timeout": self.timeout,
            "testcases": [case.as_dict() for case in self.testcase_set.all()]
        }


class TaskResult(models.Model):
    test = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    solve_status = models.CharField(max_length=20, default='no run')
    status_color = models.CharField(max_length=30, default='red')
    tests_success = models.TextField(max_length=100, default=json.dumps([]))
    submitted_code = models.TextField(max_length=1000, default=CPP_TEMPLATE)
    compile_result = models.TextField(max_length=1000, default="")


class TestCase(models.Model):
    stdin = models.TextField(default='')
    # filestring input json?
    correct_answer = models.TextField()
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return f"Question title: {self.task.title}, input: {self.stdin}, correct_answer:{self.correct_answer}"

    def as_dict(self):
        return {
            "Test_id": str(self.id),  # do we even need it? mb just dump somewhere later?
            "Stdin_input": str(self.stdin).replace('_', '').split(),
            #"Filestring json": "tbd",
            #"Output_type": "int",
            "Output_value": str(self.correct_answer)
        }


class Course(models.Model):
    tasks_pool = models.ManyToManyField(Task)
    assigned_groups = models.ManyToManyField(StudentGroup)
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=100, default='Новый курс по умолчанию')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_set', null=True)
    questions_per_student = models.SmallIntegerField(default=1)

    bracket_1 =  models.ManyToManyField(Task, related_name='task_bracket_1',   blank=True)
    bracket_2 =  models.ManyToManyField(Task, related_name='task_bracket_2',   blank=True)
    bracket_3 =  models.ManyToManyField(Task, related_name='task_bracket_3',   blank=True)
    bracket_4 =  models.ManyToManyField(Task, related_name='task_bracket_4',   blank=True)
    bracket_5 =  models.ManyToManyField(Task, related_name='task_bracket_5',   blank=True)
    bracket_6 =  models.ManyToManyField(Task, related_name='task_bracket_6',   blank=True)
    bracket_7 =  models.ManyToManyField(Task, related_name='task_bracket_7',   blank=True)
    bracket_8 =  models.ManyToManyField(Task, related_name='task_bracket_8',   blank=True)
    bracket_9 =  models.ManyToManyField(Task, related_name='task_bracket_9',   blank=True)
    bracket_10 = models.ManyToManyField(Task, related_name='task_bracket_10',  blank=True)
    bracket_11 = models.ManyToManyField(Task, related_name='task_bracket_11',  blank=True)
    bracket_12 = models.ManyToManyField(Task, related_name='task_bracket_12',  blank=True)
    bracket_13 = models.ManyToManyField(Task, related_name='task_bracket_13',  blank=True)
    bracket_14 = models.ManyToManyField(Task, related_name='task_bracket_14',  blank=True)
    bracket_15 = models.ManyToManyField(Task, related_name='task_bracket_15',  blank=True)
    bracket_16 = models.ManyToManyField(Task, related_name='task_bracket_16',  blank=True)
    bracket_17 = models.ManyToManyField(Task, related_name='task_bracket_17',  blank=True)
    bracket_18 = models.ManyToManyField(Task, related_name='task_bracket_18',  blank=True)
    bracket_19 = models.ManyToManyField(Task, related_name='task_bracket_19',  blank=True)
    bracket_20 = models.ManyToManyField(Task, related_name='task_bracket_20',  blank=True)
    bracket_21 = models.ManyToManyField(Task, related_name='task_bracket_21',  blank=True)
    bracket_22 = models.ManyToManyField(Task, related_name='task_bracket_22',  blank=True)
    bracket_23 = models.ManyToManyField(Task, related_name='task_bracket_23',  blank=True)
    bracket_24 = models.ManyToManyField(Task, related_name='task_bracket_24',  blank=True)
    bracket_25 = models.ManyToManyField(Task, related_name='task_bracket_25',  blank=True)
    bracket_26 = models.ManyToManyField(Task, related_name='task_bracket_26',  blank=True)
    bracket_27 = models.ManyToManyField(Task, related_name='task_bracket_27',  blank=True)
    bracket_28 = models.ManyToManyField(Task, related_name='task_bracket_28',  blank=True)
    bracket_29 = models.ManyToManyField(Task, related_name='task_bracket_29',  blank=True)
    bracket_30 = models.ManyToManyField(Task, related_name='task_bracket_30',  blank=True)


    @staticmethod
    def bracket_list():
        return ['bracket_' + str(i) for i in range(1, 31)]

    @staticmethod
    def bracket_dict():
        return {i: 'bracket_' + str(i) for i in range(1, 31)}
    # @property
    # def brackets(self):
    #     for i in range(self.questions_per_student):
    #         setattr(self, 'bracket_' + str(i), models.ForeignKey(Task, related_name='task_bracket'))

    def __str__(self):
        def name(s):
            l = s.split()
            new = ""
            for i in range(len(l) - 1):
                s = l[i]
                new += (s[0].upper() + '.')
            new += l[-1].title()
            return new

        try:
            author = name(self.author.get_full_name())
        except AttributeError:
            author = ''
        return f"{self.name}, {author}"

class CoursesCollection(models.Model):
    courses = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)

# class StudentGroup(models.Model):
#     group_name = models.CharField(max_length=30)
    # student = models.ForeignKey(User, on_delete=models.CASCADE)

src/django_src/teacher_controls/models.py
from django.db import models

# Create your models here.

src/django_src/teacher_controls/views.py
import json
import random

from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import CourseCreateForm, TaskCreateForm, CreateTaskModelForm, CourseManagmentForm, CourseManagment
from code_reception.models import Course, Task, TestCase
from users.models import StudentGroup

# Create your views here.

@login_required
def create_course(request):
    if request.method == "POST":
        form = CourseCreateForm(request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course.author = request.user
            try:
                if Course.objects.all().filter(name=course.name):
                    messages.error(request, f'Такой курс уже существует', extra_tags='danger')

                # add logic to assign students to this course through group
                else:
                    course.save()
                    for student_group in form.cleaned_data['assigned_groups']:
                        course.users.add(*student_group.students.all())
                    course.save()
                    messages.success(request, f'Курс успешно создан')
                    form = CourseCreateForm()
            except Exception as e:
                print(e)
                messages.error(request, f'Ошибка создания', extra_tags='danger')
        else:
            messages.error(request, f'Неправильно заполнена форма', extra_tags='danger')
            # return redirect('profile') todo: DO REDIRECT LATER
    else:
        form = CourseCreateForm()
        #form.fields['Название курса'] = form.fields.pop('name')
        #form.fields['tasks_select'] = form.fields.pop('tasks_pool')
    return render(request, 'teacher_controls/create_course.html', {'form': form})


def check_testcases_valid(testcases):
    for id, case in testcases.items():
        if not case['input'] or not case['output']:
            return False
    return True


def add_testcases_to_task(testcases, task):
    for tc_id, testcase in testcases.items():
        if testcase['testcase_type'] == 'Эталонные значения':
            new_test = TestCase(stdin=testcase['input'],
                                correct_answer=testcase['output'],
                                task=task)
            new_test.save()
            task.testcase_set.add(new_test)



@login_required
def assign_tasks(request):
    print('assign url hit')
    if request.method == 'POST':
        args = request.POST
        course_name = args['Name']
        brackets = int(args['Brackets'])
        assign_to = list(map(int, json.loads(args['Groups'])))
        tasks_by_bracket = {k: list(map(int,v)) for k, v in json.loads(args['Brackets_vals']).items()}
        course_id = int(args['Course_id'])

        course = Course.objects.all().get(id=course_id)
        groups = StudentGroup.objects.all().filter(pk__in=assign_to)

        for group in groups:
            students = group.students.all()
            course.users.add(*students)
            for stud in students:
                already_assigned = stud.task_set.all().filter(course=course)
                if len(already_assigned) != brackets:
                    stud.task_set.remove(*already_assigned)
                    for bracket_id, tasks in tasks_by_bracket.items():
                        if not tasks:
                            break
                        task = Task.objects.all().get(pk=random.choice(tasks))
                        stud.task_set.add(task)
                # for bracket in brackets:
                #     task = bracket.get_random.task()
                #     stud.task_set.add(task)


        return HttpResponse(status=200)

    else:
        return HttpResponse(status=500)

@login_required
def create_task(request):
    courses_form = CreateTaskModelForm()
    if request.method == 'POST':
        print(request.POST)  #  add_to_courses_[]
        print(request.POST.get('add_to_courses_'))
        print('post')
        form = TaskCreateForm(request.POST)
        test_cases = json.loads(request.POST.get('tests_', '{}'))
        title = request.POST.get('title_data')
        description = request.POST.get('description_data')
        print(test_cases)
        if (test_cases and title and description and check_testcases_valid(test_cases)):
            new_task = Task(title=title, text=description)
            new_task.save()
            add_testcases_to_task(test_cases, new_task)
            print('valid forms')
            messages.success(request, 'Задача успешно создана')
        else:
            print('not valid forms')
            messages.error(request, 'Необходимо заполнить все обязательные поля', extra_tags='danger')
        return render(request, 'teacher_controls/create_task.html', {'form': form, 'courses_form': courses_form})

    else:
        print('task')
        form = TaskCreateForm()

        #return HttpResponse()
    return render(request, 'teacher_controls/create_task.html', {'form': form, 'courses_form': courses_form})

@login_required
def course_controls(request, course=None):
    course_obj = Course.objects.all().get(id=course)
    if request.method == 'POST':
        try:
            course_obj.name = request.POST['Name']
            course_obj.questions_per_student = int(request.POST['Brackets'])
            course_obj.tasks_pool.set(Task.objects.all().filter(pk__in=map(int, json.loads(request.POST['Task_pool']))))
            course_obj.assigned_groups.set(StudentGroup.objects.all().filter(pk__in=map(int, json.loads(request.POST['Groups']))))

            brackets = json.loads(request.POST['Brackets_vals'])
            for idx, vals in brackets.items():
                if not vals:
                    break
                # br = getattr(course_obj, 'bracket_{}'.format(idx))
                br = Task.objects.all().filter(id__in=map(int, vals))
                # setattr(course_obj, 'bracket_{}'.format(idx), br)
                field = 'bracket_{}'.format(idx)
                eval('course_obj.{}.set(br)'.format(field))

            course_obj.save()
        except:
            messages.error(request, 'Произошла ошибка', extra_tags='danger')
            return HttpResponse(status=500)
            pass # Report error

        form = CourseManagment(instance=course_obj, course_id=course)
        print('message added')
        messages.success(request, 'Курс успешно изменен')
        return render(request, 'teacher_controls/course_controls.html',
                      {'course_name': course_obj.name, 'form': form})
        # form = CourseManagment(request.POST, course_id=course)
        # if form.is_valid():
        #     course = form.save(commit=False)
        #     course.save()
        #     messages.success(request, 'Курс успешно изменен')

        # else:
        #     messages.error(request, 'Форма неправильно заполнена', extra_tags='danger')
        #     #print(form.errors)

        # return render(request, 'teacher_controls/course_controls.html',
        #               {'course_name': course_obj.name, 'form': form})


    else:
        print('URL HIT!')
        #form = CourseManagmentForm()
        form = CourseManagment(instance=course_obj, course_id=course)
        return render(request, 'teacher_controls/course_controls.html', {'course_name': course_obj.name, 'form': form})

src/django_src/teacher_controls/templates/teacher_controls/course_controls.html
{% extends "code_reception/base.html"%}
{% block content %}
{% load crispy_forms_tags %}


<!--<form method="POST" enctype="multipart/form-data">-->
<h4>{{course_name}}</h4>
<!--<script type="text/javascript" src="/static/admin/js/jquery.min.js"></script>-->
<!--<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>-->
{{ form.media }}
<form method="POST" class="post-form"> {% csrf_token %}
{{form | crispy}}
<!--    <button type="submit" class="save btn btn-default">Save</button>-->
</form>

<button class="save btn btn-default" onclick="send('save')">Сохранить</button>
<p></p>
<button class="save btn btn-default" onclick="send('assign')">Выдать задачи</button>


<script>
    var aWhile = 800;
    var chosen_tasks = [];
    var mfn = function(){
                  var elem = document.getElementById("id_tasks_pool_to").children;
                  for (var i = 0; i < elem.length; i++){
                      console.log(elem[i].title);
                      chosen_tasks.push(elem[i].title)
                  }

                  for (var i = 1; i < 30; i++){
                    id_ = `id_bracket_${i.toString()}_from`;
                    var widg = document.getElementById(id_).children;
                    var to_remove = [];
                    for(var j = 0; j < widg.length; j++){
                        if (!chosen_tasks.includes(widg[j].title) && widg[j].value != ""){
                            to_remove.push(widg[j])
                        }
                    }
                    for (var k = 0; k < to_remove.length; k++){
                        to_remove[k].remove();
                    }
                  }
        };

    setTimeout(mfn, aWhile);
</script>

<script>
    function send(e_) {
        console.log(e_);

        function parse_shitty_widget(tag_id) {
            var options = $(`${tag_id} option`);
            var values = $.map(options ,function(option) {return option.value;});
            return values
            //var options_selected_grps = $(tag_id);
            //var values_selected_grps = $.map(options ,function(option) { return option.value; });


            //return values_selected_grps
        }

        var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();

        var name = $('#id_name')[0].value
        var brackets = $('#id_questions_per_student')[0].value
        var selected_grps = parse_shitty_widget('#id_assigned_groups_to')
        //var options_selected_grps = $('#id_assigned_groups_to option');
        //var values_selected_grps = $.map(options ,function(option) { return option.value; });

        var task_pool = parse_shitty_widget('#id_tasks_pool_to')
        // var new_task_pool = $('#id_tasks_pool_to option');
        // var task_pool_vals = $.map(options ,function(option) { return option.value; });

        var brackets_vals = {};
        try {
            for (var i = 1; i < 30; i++) {
                var _id = `#id_bracket_${i}_to`;
                brackets_vals[i] = parse_shitty_widget(_id);
            }
        }
        catch (e) {
            console.log(e);
        }

        arr = location.href.split('/')
        var course_id = arr[arr.length - 2]
        var input_dict = {
            csrfmiddlewaretoken: CSRFtoken,
            'Name': name,
            'Brackets': brackets,
            'Task_pool': JSON.stringify(task_pool),
            'Brackets_vals': JSON.stringify(brackets_vals),
            'Groups': JSON.stringify(selected_grps),
            'Course_id': course_id
        };
        //console.log(input_dict)
        //$.post("", input_dict);
        if (e_ === 'save'){
            testing_request = $.post("", input_dict);
            testing_request.fail(function () { alert('Произошла ошибка'); location.reload();});
            testing_request.done(function () { alert('Курс изменен успешно'); location.reload();});
        }
        if (e_ === 'assign'){
            testing_request = $.post("/assign_tasks/", input_dict);
            testing_request.fail(function () { alert('Произошла ошибка выдачи задач'); location.reload();});
            testing_request.done(function () { alert('Задачи выданы успешно'); location.reload();});
        }
    }
</script>

{% endblock content %}

src/django_src/teacher_controls/templates/teacher_controls/create_course.html
{% extends "code_reception/base.html"%}
{% block content %}
{% load crispy_forms_tags %}
<!--<form method="POST" enctype="multipart/form-data">-->
<script>
    console.log(123);
    window.onload = function(){
        $('#div_id_tasks_pool').children()[1].id='checkbox_parent';
        $('#checkbox_parent').wrap("<div style='height:120px; overflow-y: scroll;' class='anyClass'></div>")

        $('#div_id_assigned_groups').children()[1].id='group_select';
        $('#group_select').wrap("<div style='height:90px; overflow-y: scroll;' class='anyClass'></div>")

        $('.textinput').attr('value', '')
        console.log(321);
    }
</script>
<h2>Новый курс</h2>
<form method="POST" class="post-form">{% csrf_token %}
    {{ form| crispy}}
    <button type="submit" class="save btn btn-default">Сохранить</button>
</form>
{% endblock content %}

src/django_src/teacher_controls/templates/teacher_controls/create_task.html
{% extends "code_reception/base.html"%}
{% block content %}
{% load crispy_forms_tags %}
<!--<form method="POST" enctype="multipart/form-data">-->
<h2>Новая задача</h2>
<form method="POST" class="post-form">{% csrf_token %}
    {{ form| crispy}}
    {{courses_form | crispy}}



    <label>Тестовые сценарии*</label>
    <div id="testcases">
        <!--<hr id="line_" style="height:1px;border:none;color:#333;background-color:grey" />-->
        <hr/>
        <div id="testcase_1">
            <p></p>
            <div class="dropdown">
                <button id="testcase_1_type_btn"class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Эталонные значения
                    <span class="caret"></span>
                </button>

                <ul   class="dropdown-menu" aria-labelledby="dropdownMenu1" id="testcase_1_type">
                    <li><a href="#">Эталонные значения</a></li>
                    <li><a href="#">Python-генераторы</a></li>
                </ul>
            </div>
            <p></p>
            <div class="row">
                <div class="col-lg-6">
                    <div class="input-group">

      <span class="input-group-addon">
        <!--<input type="checkbox" aria-label="...">-->
          <label>На вход программе</label>
      </span>
                        <input id="testcase_1_in" type="text" class="form-control" aria-label="...">
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="input-group">
      <span class="input-group-addon">
        <label>Правильный ответ</label>
      </span>
                        <input id="testcase_1_out" type="text" class="form-control" aria-label="...">
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
        </div>
    </div> <!--  end of widget -->

    <p></p>

    <!--<button class="add_field_button btn btn-success btn-md"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>-->

    <!--<p></p>-->

</form>
<button class="add_field_button btn btn-success" onclick="fn()"><label class="glyphicon glyphicon-plus"></label></button>
<br></br>
<button onclick="send()" class="save btn btn-default">Сохранить</button>


<script>
    var global_var = 1
    function fn(){
        if (typeof fn.counter == 'undefined' ){
            fn.counter = 1;
        }
        fn.counter ++;
        if (typeof fn.html == 'undefined' ){
            fn.html = $("#testcases").html();
        }
        console.log(fn.counter)
        html = fn.html
        html = html.replace(`testcase_1`, `testcase_${fn.counter}`) // testcase_1_type
        html = html.replace(`testcase_1_type`, `testcase_${fn.counter}_type`)
        html = html.replace(`testcase_1_type_btn`, `testcase_${fn.counter}_type_btn`)
        html = html.replace(`testcase_1_in`, `testcase_${fn.counter}_in`)
        html = html.replace(`testcase_1_out`, `testcase_${fn.counter}_out`)
        $("#testcases").append(html);
        global_var = fn.counter;

    }
    function send(){
        var title = $('input[name*=title]')[0].value
        var description = $('textarea[name*=text]')[0].value
        var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();
        var add_to_courses = []
        var courses_selected = $('select[name*=courses]').children("option:selected")
        for (var i = 0; i < courses_selected.length; i++){
            add_to_courses.push(courses_selected[i].value)
        }
        var testcases = {
        }
        for (var i = 1; i <= global_var; i++){
            testcases[i] = {
                testcase_type: $(`#testcase_${i}_type_btn`)[0].innerHTML.replace('<span class="caret"></span>', '').trim(),
                input: $(`#testcase_${i}_in`)[0].value,
                output: $(`#testcase_${i}_out`)[0].value,

            }
        }

        var input_dict = {
            csrfmiddlewaretoken: CSRFtoken,
            tests_: JSON.stringify(testcases),
            title_data: title,
            description_data: description,
            add_to_courses_: JSON.stringify(add_to_courses)

        };
        console.log(input_dict)
        $.post("", input_dict);

    }
    $(".dropdown-menu li a").click(function(){
        $(this).parents(".dropdown").find('.btn').html($(this).text() + ' <span class="caret"></span>');
        $(this).parents(".dropdown").find('.btn').val($(this).data('value'));});
</script>

{% endblock content %}